// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignityQuest.Models;

#nullable disable

namespace SignityQuest.Migrations
{
    [DbContext(typeof(TasksDBContext))]
    partial class TasksDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SignityQuest.Models.DBPreviousTasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<DateTime>("firstOccurrenceDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("nextOccurrenceDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("previousOccurenceDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("todaysDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("DBPreviousTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
